spring:
  h2:
    console:
      enabled: true
      path: /h2-console
#      settings:
#        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:jinsite;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true


  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 2000
        default-page-size: 20

jinsite:
  jwt-key: "3ZIagOxhx+NOvMS70FzYns7j2tjd07GO5yuyHgjFcds="





